# Generated by Django 5.1.1 on 2024-11-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aliases',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='whitelists',
        ),
        migrations.AddField(
            model_name='file',
            name='summary',
            field=models.CharField(default=None, max_length=65536, null=True),
        ),
    ]
