# Generated by Django 5.1.7 on 2025-03-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ai_describes_incident',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='ai_incident_classification',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='ai_incident_summary',
            field=models.CharField(default=None, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
