# Generated by Django 5.1 on 2024-09-06 13:29

import stixify.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='markdown_file',
            field=models.FileField(null=True, upload_to=stixify.web.models.upload_to_func),
        ),
    ]
