# Generated by Django 5.1 on 2024-10-11 09:00

import django.db.models.deletion
import stixify.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_profile_defang_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=stixify.web.models.upload_to_func)),
                ('name', models.CharField(max_length=256)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.file')),
            ],
        ),
    ]
