# Generated by Django 5.1.1 on 2024-11-16 11:22

import stixify.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_profile_aliases_remove_profile_whitelists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='Full path to the file to be converted. Must match a supported file type: `application/pdf`, `application/msword`, `application/vnd.openxmlformats-officedocument.wordprocessingml.document`, `application/vnd.ms-powerpoint`, `application/vnd.openxmlformats-officedocument.presentationml.presentation`, `text/html`, `text/csv`, `image/jpg`, `image/jpeg`, `image/png`, `image/webp`. The filetype must be supported by the `mode` used or you will receive an error.', max_length=1024, upload_to=stixify.web.models.upload_to_func),
        ),
        migrations.AlterField(
            model_name='file',
            name='markdown_file',
            field=models.FileField(max_length=256, null=True, upload_to=stixify.web.models.upload_to_func),
        ),
        migrations.AlterField(
            model_name='file',
            name='mimetype',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='fileimage',
            name='file',
            field=models.ImageField(max_length=256, upload_to=stixify.web.models.upload_to_func),
        ),
    ]
