# Generated by Django 5.1 on 2024-10-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_fileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='defang',
            field=models.BooleanField(help_text='If the text should be defanged before processing'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='defang',
            field=models.BooleanField(help_text='If the text should be defanged before processing'),
        ),
    ]
