# Generated by Django 5.1.7 on 2025-04-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0003_alter_file_ai_incident_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='tlp_level',
            field=models.CharField(choices=[('red', 'Red'), ('amber+strict', 'Amber Strict'), ('amber', 'Amber'), ('green', 'Green'), ('clear', 'Clear')], default='red', help_text='This will be assigned to all SDOs and SROs created. If no value passed, `TLP:Clear` will be assigned.'),
        ),
    ]
