# Generated by Django 5.1.1 on 2024-11-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_profile_ignore_image_refs_profile_ignore_link_refs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='ai_summary_provider',
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_summary_provider',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
