# Generated by Django 5.1 on 2024-10-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_dossier_created_remove_dossier_identity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='defang',
        ),
    ]
