# Generated by Django 5.1 on 2024-10-29 15:51

import stixify.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_file_defang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='created_by_ref',
            field=models.JSONField(default=stixify.web.models.default_identity, validators=[stixify.web.models.validate_identity]),
        ),
        migrations.AlterField(
            model_name='file',
            name='identity',
            field=models.JSONField(default=stixify.web.models.default_identity, help_text='This is a full STIX Identity JSON. e.g. `{"type":"identity","spec_version":"2.1","id":"identity--9779a2db-f98c-5f4b-8d08-8ee04e02dbb5","created":"2020-01-01T00:00:00.000Z","modified":"2020-01-01T00:00:00.000Z","name":"dogesec","description":"https://github.com/muchdogsec/","identity_class":"organization","sectors":["technology"],"contact_information":"https://www.dogesec.com/contact/","object_marking_refs":["marking-definition--94868c89-83c2-464b-929b-a1a8aa3c8487","marking-definition--97ba4e8b-04f6-57e8-8f6e-3a0f0a7dc0fb"]}`', validators=[stixify.web.models.validate_identity]),
        ),
    ]
