# Generated by Django 5.2.3 on 2025-07-30 11:56

import stixify.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0006_file_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='markdown_file',
            field=models.FileField(max_length=1024, null=True, upload_to=stixify.web.models.upload_to_func),
        ),
        migrations.AlterField(
            model_name='file',
            name='pdf_file',
            field=models.FileField(max_length=1024, null=True, upload_to=stixify.web.models.upload_to_func),
        ),
        migrations.AlterField(
            model_name='fileimage',
            name='file',
            field=models.ImageField(max_length=1024, upload_to=stixify.web.models.upload_to_func),
        ),
    ]
