# Generated by Django 5.2.3 on 2025-07-30 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0006_file_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stixify_core.file'),
        ),
    ]
