# Generated by Django 5.1.1 on 2025-01-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_file_ai_summary_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ignore_extraction_boundary',
            field=models.BooleanField(default=False),
        ),
    ]
