# Generated by Django 5.1.5 on 2025-02-06 06:35

import stixify.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_profile_ignore_extraction_boundary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='dossiers',
        ),
        migrations.AddField(
            model_name='profile',
            name='ignore_embedded_relationships',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='ignore_embedded_relationships_smo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ignore_embedded_relationships_sro',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=1024, upload_to=stixify.web.models.upload_to_func),
        ),
        migrations.AlterField(
            model_name='file',
            name='mode',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='Dossier',
        ),
    ]
