# Generated by Django 5.1 on 2024-10-30 10:29

import stixify.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_dossier_created_by_ref_alter_file_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='identity',
            field=models.JSONField(default=stixify.web.models.default_identity, help_text='This is a full STIX Identity JSON. e.g. `{"type":"identity","spec_version":"2.1","id":"identity--b1ae1a15-6f4b-431e-b990-1b9678f35e15","name":"Dummy Identity"}`', validators=[stixify.web.models.validate_identity]),
        ),
    ]
