# Generated by Django 5.1 on 2024-10-30 13:16

import django.contrib.postgres.fields
import dogesec_commons.stixifier.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_file_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, validators=[functools.partial(dogesec_commons.stixifier.models.validate_extractor, *(['alias'],), **{})]), default=list, help_text='alias id(s)', size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='extractions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, validators=[functools.partial(dogesec_commons.stixifier.models.validate_extractor, *(['ai', 'pattern', 'lookup'],), **{})]), help_text='extraction id(s)', size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whitelists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, validators=[functools.partial(dogesec_commons.stixifier.models.validate_extractor, *(['whitelist'],), **{})]), default=list, help_text='whitelist id(s)', size=None),
        ),
    ]
