# Generated by Django 5.2.4 on 2025-10-07 15:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0008_alter_job_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=256), default=None, null=True, size=None),
        ),
    ]
