# Generated by Django 5.1 on 2024-10-30 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_profile_aliases_alter_profile_extractions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='report_id',
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
