# Generated by Django 5.2.8 on 2025-12-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0009_file_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extra',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('import-file', 'Import File'), ('sync-vulnerabilities', 'Sync Vulnerabilities')], default='import-file', max_length=64),
        ),
    ]
