# Generated by Django 5.2.8 on 2026-01-06 11:01

import contextlib
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
from dogesec_commons.identity.serializers import IdentitySerializer

import typing
if typing.TYPE_CHECKING:
    from stixify import settings


def list_identities(self, request, *args, **kwargs):
    from dogesec_commons.objects.helpers import ArangoDBHelper

    helper = ArangoDBHelper(settings.VIEW_NAME, None)
    query = """
        FOR doc IN stixify_vertex_collection
        FILTER doc.type IN ["identity", "report"] AND doc._is_latest == TRUE
        RETURN KEEP(doc, KEYS(doc, TRUE))
        """
    data = helper.execute_query(query, paginate=False)
    reports = []
    id_map = {}
    for d in data:
        if d["type"] == "report":
            reports.append([d['id'], d['created_by_ref']])
        else:
            id_map[d["id"]] = d
    for report in reports:
        identity = id_map.get(report[1])
        if identity:
            yield report[0], identity


def make_default_identity(apps, schema_editor):
    import uuid
    from types import SimpleNamespace
    from stix2arango.stix2arango import Stix2Arango
    s2a = Stix2Arango(
        settings.ARANGODB_DATABASE,
        "stixify",
        None,
        True,
        True,
        username=settings.ARANGODB_USERNAME,
        password=settings.ARANGODB_PASSWORD,
        host_url=settings.ARANGODB_HOST_URL,
    )
    return create_or_get_identity(settings.STIX_IDENTITY)

def create_or_get_identity(identity_data):
    from dogesec_commons.identity.models import Identity
    identity_instance = Identity.objects.filter(id=identity_data["id"]).first()
    if not identity_instance:
        serializer = IdentitySerializer(data=identity_data)
        identity_instance = serializer.is_valid(raise_exception=True)
        identity_instance: Identity = serializer.save()
    return identity_instance

def copy_identities_to_local(apps, schema_editor):
    from dogesec_commons.identity.models import Identity as CommonIdentity
    from stixify.web.models import File

    FileType: type[File] = apps.get_model("stixify_core", "File")

    Identity: type[CommonIdentity] = apps.get_model("dogesec_identity", "Identity")
    identities = list_identities(None, None)

    for report_id, identity_data in identities:
        _, _, report_id = report_id.rpartition("--")
        identity_instance = create_or_get_identity(identity_data)
        FileType.objects.filter(id=report_id).update(
            identity=identity_instance
        )


class Migration(migrations.Migration):

    dependencies = [
        ("stixify_core", "0010_job_extra_job_type"),
        ("dogesec_identity", "__first__"),
    ]
    operations = [
        migrations.RemoveField(
            model_name="file",
            name="identity",
        ),
        migrations.RunPython(
            code=make_default_identity,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="file",
            name="identity",
            field=models.ForeignKey(
                default=settings.STIX_IDENTITY["id"],
                on_delete=django.db.models.deletion.CASCADE,
                to="dogesec_identity.identity",
            ),
        ),
        migrations.RunPython(
            code=copy_identities_to_local,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
