# Generated by Django 5.2.9 on 2026-01-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogesec_identity', '0001_initial'),
        ('stixify_core', '0011_migrate_to_local_identities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='identity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dogesec_identity.identity'),
        ),
    ]
