# Generated by Django 5.2.11 on 2026-03-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0012_alter_file_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='confidence',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
