# Generated by Django 5.2.8 on 2026-03-17 00:00

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0013_alter_file_confidence'),
    ]

    operations = [
        # Enable the pg_trgm extension for trigram operations
        TrigramExtension(),
        migrations.CreateModel(
            name='ObjectValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stix_id', models.CharField(db_index=True, max_length=256)),
                ('type', models.CharField(db_index=True, max_length=256)),
                ('ttp_type', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('values', models.JSONField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_values', to='stixify_core.file')),
                ('created', models.DateTimeField(default=None, null=True)),
                ('modified', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(fields=['stix_id', 'type'], name='stixify_s_stix_id_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='objectvalue',
            unique_together={('stix_id', 'file')},
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION jsonb_values_concat(j jsonb)
            RETURNS text
            LANGUAGE sql
            IMMUTABLE
            PARALLEL SAFE
            AS $$
                SELECT string_agg(value, ' ')
                FROM jsonb_each_text(j)
            $$;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS jsonb_values_concat(jsonb);",
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX idx_objectvalue_values_trgm
            ON stixify_core_objectvalue
            USING gin (jsonb_values_concat(values) gin_trgm_ops);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_objectvalue_values_trgm;
            """,
        ),
    ]
