# Generated by Django 5.2.12 on 2026-03-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0014_objectvalue_jsonb_values_concat_function'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectvalue',
            old_name='ttp_type',
            new_name='knowledgebase',
        ),
    ]
