# Generated by Django 5.2.12 on 2026-03-27 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
        ('stixify_core', '0015_rename_ttp_type_objectvalue_knowledgebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='embedding',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.documentembedding'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('import-file', 'Import File'), ('sync-vulnerabilities', 'Sync Vulnerabilities'), ('build-clusters', 'Build Clusters'), ('build-embeddings', 'Build Embeddings')], default='import-file', max_length=64),
        ),
    ]
