# Generated by Django 5.2.11 on 2026-04-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0018_objectvalue_generated_fields_and_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION jsonb_values_concat(j jsonb)
            RETURNS text
            LANGUAGE sql
            IMMUTABLE
            PARALLEL SAFE
            AS $$
                SELECT string_agg(LOWER(value), ' ')
                FROM jsonb_each_text(j)
            $$;
            """,
            reverse_sql=""
        ),
        migrations.RunSQL(
            """
            DROP INDEX IF EXISTS ctx_values_list_idx;
            CREATE INDEX ctx_values_list_idx
            ON stixify_core_objectvalue
            USING gin (values_list array_ops, type gin_trgm_ops) WHERE NOT is_dupe;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            DROP INDEX IF EXISTS ctx_values_concat_idx;
            CREATE INDEX ctx_values_concat_idx
            ON stixify_core_objectvalue
            USING gin (values_concat gin_trgm_ops, type gin_trgm_ops) WHERE NOT is_dupe;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]