# Generated by Django 5.2.12 on 2026-05-22 12:24

from django.db import migrations, models

def rename_sync_tasks(apps, schema_editor):
    Job = apps.get_model('stixify_core', 'Job')
    Job.objects.filter(type='sync-vulnerabilities').update(type='sync-knowledgebase', extra=dict(knowledgebase='cve'))


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0019_add_index_on_values_list'),
    ]

    operations = [

        migrations.RunPython(
            rename_sync_tasks,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('import-file', 'Import File'), ('sync-knowledgebase', 'Sync Knowledgebase'), ('build-clusters', 'Build Clusters'), ('build-embeddings', 'Build Embeddings')], default='import-file', max_length=64),
        ),
    ]
