# Generated by Django 5.2.12 on 2026-05-26 11:56

import datetime
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0020_alter_job_type'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION jsonb_sort_value(j jsonb, extra_text text)
            RETURNS text
            LANGUAGE sql
            IMMUTABLE
            PARALLEL SAFE
            AS $$
                SELECT SUBSTR(LOWER(value), 1, 32) || '+' || extra_text
                FROM jsonb_each_text(j)
                LIMIT 1
            $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='stixify_ov_values_concat_idx',
        ),
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='stixify_ov_values_c_kbidx',
        ),
        migrations.AddField(
            model_name='objectvalue',
            name='values_sort',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('values'), django.db.models.functions.comparison.Cast(models.F('id'), models.TextField()), function='jsonb_sort_value'), null=True, output_field=models.CharField(max_length=48)),
        ),
        migrations.AlterField(
            model_name='objectvalue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='objectvalue',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(models.F('values_sort'), models.F('id'), models.F('type'), condition=models.Q(('is_dupe', False)), name='stixify_ov_values_concat_idx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(models.F('values_sort'), models.F('id'), models.F('knowledgebase'), condition=models.Q(('is_dupe', False)), name='stixify_ov_values_c_kbidx'),
        ),
    ]
