# Generated by Django 5.2.12 on 2026-05-26 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0021_remove_objectvalue_stixify_ov_values_concat_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('import-file', 'Import File'), ('reprocess-posts', 'Reprocess Posts'), ('sync-knowledgebase', 'Sync Knowledgebase'), ('build-clusters', 'Build Clusters'), ('build-embeddings', 'Build Embeddings')], default='import-file', max_length=64),
        ),
        migrations.AlterField(
            model_name='job',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stixify_core.file'),
        ),
    ]
