# Generated by Django 5.2.12 on 2026-06-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0022_alter_job_type_job_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(fields=['file_id', 'knowledgebase'], name='stixify_ov_kb_stats'),
        ),
    ]
