# Generated by Django 5.2.12 on 2026-07-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0023_objectvalue_stixify_ov_kb_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='admiralty_information_credibility',
            field=models.CharField(choices=[('1', '1 - Confirmed by other sources'), ('2', '2 - Probably true'), ('3', '3 - Possibly true'), ('4', '4 - Doubtful'), ('5', '5 - Improbable'), ('6', '6 - Truth cannot be judged')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='admiralty_source_reliability',
            field=models.CharField(choices=[('A', 'A - Completely reliable'), ('B', 'B - Usually reliable'), ('C', 'C - Fairly reliable'), ('D', 'D - Not usually reliable'), ('E', 'E - Unreliable'), ('F', 'F - Reliability cannot be judged')], default=None, max_length=1, null=True),
        ),
    ]
