# Generated by Django 5.2.12 on 2026-07-28 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stixify_core", "0024_file_admiralty_information_credibility_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
