# Generated by Django 5.2.12 on 2026-07-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0025_alter_file_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pap_level',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green'), ('clear', 'Clear'), ('white', 'White')], default=None, help_text='This will be assigned to all SDOs and SROs created. If no value passed, no PAP marking will be assigned.', max_length=16, null=True),
        ),
    ]
