# Generated by Django 5.2.12 on 2026-08-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stixify_core', '0028_rename_reprocess_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
